// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VisitorsLibrary.Models
{
    public partial class Visitor
    {
        public Visitor()
        {
            VisitorLog = new HashSet<VisitorLog>();
        }

        public int VisitorIdentifier { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public virtual ICollection<VisitorLog> VisitorLog { get; set; }
        public override string ToString() => $"{VisitorIdentifier,-4} {FirstName} {LastName}";
    }
}