// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using VisitorsLibrary.Extensions;

namespace VisitorsLibrary.Models
{
    public partial class VisitorLog
    {
        public int VistorLogIdentifier { get; set; }
        public int? VisitorIdentifier { get; set; }
        public DateOnly? VisitOn { get; set; }
        public TimeSpan? EnteredTime { get; set; }
        public TimeSpan? ExitedTime { get; set; }
        public TimeSpan Spent => EnteredTime.Elapsed(ExitedTime);
        public virtual Visitor Navigation { get; set; }
        public override string ToString() => $"{VistorLogIdentifier,-4}{VisitorIdentifier}";
    }
}