// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using VisitorsLibrary.Models;

namespace VisitorsLibrary.Data.Configurations;

public partial class VisitorLogConfiguration : IEntityTypeConfiguration<VisitorLog>
{
    public void Configure(EntityTypeBuilder<VisitorLog> entity)
    {
        entity.HasKey(e => e.VistorLogIdentifier);

        entity.Property(e => e.VisitOn).HasColumnType("date");

        entity.HasOne(d => d.Navigation)
            .WithMany(p => p.VisitorLog)
            .HasForeignKey(d => d.VisitorIdentifier)
            .HasConstraintName("FK_VisitorLog_Visitor");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<VisitorLog> entity);
}